version: 2.1
orbs:
  windows: circleci/windows@2.4.0
jobs:
  build-windows:
    executor: windows/gpu-nvidia
    steps:
      - checkout
      - run: systeminfo
workflows:
  windows-workflow:
    jobs:
      - build-windows