version: 2.1
orbs:
  windows: circleci/windows@2.4.0
jobs:
  build-windows:
    machine:
      image: windows-server-2019-nvidia:stable
      resource_class: windows.medium
      shell: powershell.exe -ExecutionPolicy Bypass
    steps:
      - checkout
      - run: systeminfo